version: '3'
services:
  backend:
    build: ./doctor-office-backend
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    env_file:
      - .env

  frontend:
    build: ./doctor-office-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
