apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 390844769589.dkr.ecr.us-east-1.amazonaws.com/midterm/backend:latest
          ports:
          - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.5
              memory: 350Mi
            limits:
              cpu: 1
              memory: 450Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 150Mi